# Generated by Django 5.0.4 on 2024-05-10 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Juries',
            fields=[
                ('jury_username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nationality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.IntegerField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('stadium_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stadium_name', models.CharField(max_length=100)),
                ('stadium_country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vb_app.team')),
                ('coach_username', models.CharField(max_length=50)),
                ('contract_start', models.DateField()),
                ('contract_finish', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchSession',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stadium_id', models.IntegerField(null=True)),
                ('time_slot', models.DateTimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('assigned_jury_username', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='vb_app.juries')),
            ],
            options={
                'unique_together': {('stadium_id', 'time_slot', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='vb_app.users')),
            ],
        ),
        migrations.AddField(
            model_name='juries',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jury', to='vb_app.users'),
        ),
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('coach_username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nationality', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='vb_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vb_app.team')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_app.channel')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedTo',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vb_app.matchsession')),
                ('assigned_jury_username', models.CharField(max_length=50)),
                ('rating', models.IntegerField(null=True)),
                ('stadium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vb_app.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='PlaysIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_username', models.CharField(max_length=50)),
                ('team_type', models.CharField(max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_app.team')),
            ],
            options={
                'unique_together': {('player_username', 'team')},
            },
        ),
        migrations.CreateModel(
            name='PlayerPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_positions_ID', models.CharField(max_length=50, null=True)),
                ('player_username', models.CharField(max_length=50, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_app.position')),
            ],
            options={
                'unique_together': {('player_username', 'position')},
            },
        ),
        migrations.CreateModel(
            name='PlayerInMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vb_app.matchsession')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vb_app.players')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vb_app.position')),
            ],
            options={
                'unique_together': {('session', 'player')},
            },
        ),
        migrations.CreateModel(
            name='PlayedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.IntegerField()),
                ('date', models.DateField()),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vb_app.matchsession')),
                ('stadium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vb_app.stadium')),
            ],
            options={
                'unique_together': {('stadium', 'session', 'time_slot', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PlayedBy',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vb_app.matchsession')),
                ('date', models.DateField()),
                ('time_slot', models.IntegerField()),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vb_app.team')),
            ],
            options={
                'unique_together': {('team', 'date', 'time_slot')},
            },
        ),
    ]
