# Generated by Django 5.0.4 on 2024-05-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vb_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatabaseManagers',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
