# Generated by Django 5.0.4 on 2024-05-10 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsession',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vb_app.team'),
        ),
    ]
