# Generated by Django 5.0.4 on 2024-05-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb_app', '0002_matchsession_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coaches',
            name='user',
        ),
        migrations.RemoveField(
            model_name='juries',
            name='user',
        ),
        migrations.RemoveField(
            model_name='players',
            name='user',
        ),
        migrations.RenameField(
            model_name='coaches',
            old_name='coach_username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='juries',
            old_name='jury_username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='players',
            old_name='player_username',
            new_name='username',
        ),
        migrations.AddField(
            model_name='coaches',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coaches',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coaches',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='juries',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='juries',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='juries',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
