# Generated by Django 5.0.4 on 2024-05-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vb_app', '0002_delete_databasemanagers_delete_player_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('surname', models.TextField(blank=True, null=True)),
                ('nationality', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'Coach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dbmanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DBManager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('surname', models.TextField(blank=True, null=True)),
                ('nationality', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'Jury',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matchsession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.BigIntegerField(blank=True, db_column='session_ID', null=True)),
                ('team_id', models.BigIntegerField(blank=True, db_column='team_ID', null=True)),
                ('stadium_id', models.BigIntegerField(blank=True, db_column='stadium_ID', null=True)),
                ('stadium_name', models.TextField(blank=True, null=True)),
                ('stadium_country', models.TextField(blank=True, null=True)),
                ('time_slot', models.BigIntegerField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('assigned_jury_username', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MatchSession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('surname', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.TextField(blank=True, null=True)),
                ('height', models.BigIntegerField(blank=True, null=True)),
                ('weight', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playerpositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_positions_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('position', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PlayerPositions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playerteams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_teams_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('team', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PlayerTeams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.BigIntegerField(blank=True, db_column='position_ID', null=True)),
                ('position_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessionsquads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_id', models.BigIntegerField(blank=True, db_column='squad_ID', null=True)),
                ('session_id', models.BigIntegerField(blank=True, db_column='session_ID', null=True)),
                ('played_player_username', models.TextField(blank=True, null=True)),
                ('position_id', models.BigIntegerField(blank=True, db_column='position_ID', null=True)),
            ],
            options={
                'db_table': 'SessionSquads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.BigIntegerField(blank=True, db_column='team_ID', null=True)),
                ('team_name', models.TextField(blank=True, null=True)),
                ('coach_username', models.TextField(blank=True, null=True)),
                ('contract_start', models.TextField(blank=True, null=True)),
                ('contract_finish', models.TextField(blank=True, null=True)),
                ('channel_id', models.BigIntegerField(blank=True, db_column='channel_ID', null=True)),
                ('channel_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Team',
                'managed': False,
            },
        ),
    ]
