# Generated by Django 5.0.4 on 2024-05-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vb_app', '0004_alter_players_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerpositions',
            old_name='player_username',
            new_name='username',
        ),
        migrations.AlterUniqueTogether(
            name='playerpositions',
            unique_together={('username', 'position')},
        ),
    ]
