# Generated by Django 5.0.4 on 2024-05-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vb_app', '0005_rename_player_username_playerpositions_username_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchsession',
            unique_together={('session_id', 'team')},
        ),
         migrations.AlterUniqueTogether(
            name='playedin',
            unique_together={('stadium', 'time_slot', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='playsin',
            unique_together={('username', 'team')},
        ),
    ]
