# Generated by Django 5.0.4 on 2024-05-11 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb_app', '0006_rename_player_username_playsin_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedin',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vb_app.matchsession', unique=True),
        ),
    ]
