# Generated by Django 5.0.4 on 2024-05-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vb_app', '0007_rename_player_username_playsin_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playsin',
            old_name='team',
            new_name='team_id',
        ),
        migrations.AlterUniqueTogether(
            name='playsin',
            unique_together={('username', 'team_id')},
        ),
    ]
