# Generated by Django 5.0.4 on 2024-05-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vb_app', '0008_rename_team_playsin_team_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchsession',
            name='assigned_jury_username',
        ),
        migrations.RemoveField(
            model_name='matchsession',
            name='date',
        ),
        migrations.RemoveField(
            model_name='matchsession',
            name='stadium_id',
        ),
        migrations.RemoveField(
            model_name='matchsession',
            name='time_slot',
        ),
        migrations.AlterUniqueTogether(
            name='playsin',
            unique_together={('username', 'team')},
        ),
        migrations.RemoveField(
            model_name='playsin',
            name='team_type',
        ),
    ]
