# Generated by Django 5.0.4 on 2024-05-11 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb_app', '0011_rename_player_playerinmatch_player_username_and_more'),
    ]

    operations = [
    ]
