services:
  db:
    container_name: volleyball_db
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'  # Use port 3307 on the host to avoid port conflict
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-ppassword", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
    volumes:
      - ./mydb2:/var/lib/mysql


